completed enabling fileio.ts calculations.ts fetch.ts and server.ts to work together to complete output

diff --git a/src/run b/src/run
--- a/src/run
+++ b/src/run
@@ -2,30 +2,59 @@
 
 # need to add writes to log file
 # check if input is install
-if [ "$1" = "install" ]
-then
+if [ "$1" = "install" ]; then
     # install dependencies
-    npm install typescript &> './dev/null'
-    npm install typescript ts-node &> './dev/null'
-    npm install axios &> './dev/null'
-    npm install winston &> './dev/null'
-    npm install dotenv &> './dev/null'
-    # add check for successful install
-    echo "4 dependencies installed"
-    # need to change exit code to be based on if install was successful
-    exit 0
+    TSERR=$(npm install typescript 2>&1 > '/dev/null')
+    TSNODEERR=$(npm install typescript ts-node 2>&1 > '/dev/null')
+    AXIOSERR=$(npm install axios 2>&1 > '/dev/null')
+    WINSTONERR=$(npm install winston 2>&1 > '/dev/null')
+    DOTENVERR=$(npm install dotenv 2>&1 > '/dev/null')
+    NDJSON=$(npm install --save @types/ndjson 2>&1 > '/dev/null')
+    # check for successful installs
+    if [[ $TSERROR != '' ]]; then
+        echo 'Error installing typescript'
+        exit 1
+    elif [[ $TSNODEERR != '' ]]; then
+        echo 'Error installing typescript ts-node'
+        exit 1
+    elif [[ $AXIOSERR != '' ]]; then
+        echo 'Error installing axios'
+        exit 1
+    elif [[ $WINSTONERR != '' ]]; then
+        echo 'Error installing winston'
+        exit 1
+    elif [[ $DOTENVERR != '' ]]; then
+        echo 'Error installing dotenv'
+        exit 1
+    elif [[ $NDJSON != '' ]]; then
+        echo 'Error installing ndjson type'
+        exit 1
+    else
+        echo "6 dependencies successfully installed"
+        exit 0
+    fi
 
 # check if input is a file
 elif [ -f "$1" ]
 then
-    tsc *.ts
-    node main.js "$1"
-    exit 0
+    TSC=$(tsc main.ts fetch.ts fileio.ts calculations.ts logging_cfg.ts 2>&1 > '/dev/null');
+    if [ $TSC != '' ]; then
+        echo "Files failed to compile"
+        exit 1
+    else
+        MAIN=$(node main.js "$1" 2>&1 '/dev/null')
+        if [ $MAIN != '' ]; then
+            exit 1
+            echo "Files failed to run"
+        else
+            exit 0
+        fi
+    fi
 
 # check if input is test
 elif [ "$1" = "test" ]
 then
-    echo "Running the test suite"
+    #echo "Running the test suite"
     #insert call to test suite
     exit 0
 
