update calculations.test.ts

diff --git a/src/run b/src/run
--- a/src/run
+++ b/src/run
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-#source .env
 # need to add writes to log file
 # check if input is install
 if [ "$1" = "install" ]; then
@@ -10,7 +9,8 @@ if [ "$1" = "install" ]; then
     AXIOSERR=$(npm install axios 2>&1 > '/dev/null')
     WINSTONERR=$(npm install winston 2>&1 > '/dev/null')
     DOTENVERR=$(npm install dotenv 2>&1 > '/dev/null')
-    NDJSON=$(npm install --save @types/ndjson 2>&1 > '/dev/null')
+    NDJSONERR=$(npm install --save @types/ndjson 2>&1 > '/dev/null')
+    JESTERR=$(npm install jest 2>&1 > '/dev/null')
     # check for successful installs
     if [[ $TSERROR != '' ]]; then
         echo 'Error installing typescript'
@@ -27,8 +27,11 @@ if [ "$1" = "install" ]; then
     elif [[ $DOTENVERR != '' ]]; then
         echo 'Error installing dotenv'
         exit 1
-    elif [[ $NDJSON != '' ]]; then
+    elif [[ $NDJSONERR != '' ]]; then
         echo 'Error installing ndjson type'
+        exit 1
+    elif [[ $JESTERR != '' ]]; then
+        echo 'Error installing jest'
         exit 1
     else
         echo "6 dependencies successfully installed"
@@ -53,18 +56,25 @@ then
             node main.js $1
             exit 0
         fi
-        #if [ -f "${LOG_FILE}" ]; then
-        #    node main.js $1
-        #    exit 0
-        #else
-        #    echo "Provide valid Log File"
-        #    exit 1
-        #fi
     fi
 
 # check if input is test
 elif [ "$1" = "test" ]
 then
+
+    #TEST=$(npx jest --collectCoverage --coverageReporters="json-summary" 2>&1 > '/dev/null')
+    #TEST=$(npx jest --collectCoverage --coverageReporters="json-summary" 2>&1 | tee /dev/tty)
+    #echo $TEST
+    #echo $COVERAGE_REPORT
+    #coverage_report=$(npx jest calculations.test.ts --coverage)
+    #line_coverage=$(echo "$coverage_report" | grep -oP 'Lines:\s+\K[0-9.]+%' | sed 's/%//')
+
+    #echo "Line coverage: $line_coverage"
+    #COVERAGE_RAW=$(npx jest calculations.test.ts --coverage --coverageReporters="text-summary" )
+    #echo "$COVERAGE_RAW" | awk -F'/| ' '/Branches/{print $(NF-1)}'
+
+    # COVERAGE=$(npx jest calculations.test.ts --coverage --silent)
+    #echo $COVERAGE
     #echo "Running the test suite"
     #insert call to test suite
     exit 0
